version: '3'

services:
  db:
    build:
      context: ./mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MY_SQL_USER=root
    networks:
      - node-network

  node: 
    build:
      context: ./node
      dockerfile: Dockerfile
    image: brunogsantos/node
    container_name: app
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: brunogsantos/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
networks:
  node-network:
    driver: bridge